# Generated by Django 5.1.15 on 2026-04-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alu_id', models.AutoField(primary_key=True, serialize=False)),
                ('alu_nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('alu_documento', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('alu_data_nascimento', models.DateField(verbose_name='data de nascimento')),
                ('alu_endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='endereço')),
                ('alu_email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='e-mail')),
                ('alu_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('alu_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso (kg)')),
                ('alu_massa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='massa muscular (kg)')),
                ('alu_massa_gorda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='massa gorda (kg)')),
                ('alu_porcentagem_gordura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% gordura')),
                ('alu_circunferencia_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='circunferência abdominal (cm)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'db_table': 'alunos',
                'ordering': ['alu_nome'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoTurmas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agtu_id', models.AutoField(primary_key=True, serialize=False)),
                ('agtu_dias_disponiveis', models.CharField(max_length=100, verbose_name='dias disponíveis')),
                ('agtu_horarios_disponiveis', models.CharField(max_length=200, verbose_name='horários disponíveis')),
                ('agtu_nivelamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='nivelamento')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('alu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.aluno', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'Agendamento de Turma',
                'verbose_name_plural': 'Agendamentos de Turmas',
                'db_table': 'agendamento_turmas',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoHorario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('agho_id', models.AutoField(primary_key=True, serialize=False)),
                ('agho_dias_disponiveis', models.CharField(max_length=100, verbose_name='dias disponíveis')),
                ('agho_horarios_disponiveis', models.CharField(max_length=200, verbose_name='horários disponíveis')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('alu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.aluno', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'Agendamento de Horário',
                'verbose_name_plural': 'Agendamentos de Horário',
                'db_table': 'agendamento_horario',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('prof_id', models.AutoField(primary_key=True, serialize=False)),
                ('prof_nome', models.CharField(max_length=100, unique=True, verbose_name='profissão')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissão',
                'verbose_name_plural': 'Profissões',
                'db_table': 'profissao',
                'ordering': ['prof_nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('func_id', models.AutoField(primary_key=True, serialize=False)),
                ('func_nome', models.CharField(max_length=150, verbose_name='nome completo')),
                ('func_documento', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('func_endereco', models.CharField(blank=True, max_length=300, null=True, verbose_name='endereço')),
                ('func_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone')),
                ('func_formacao', models.CharField(blank=True, max_length=200, null=True, verbose_name='formação acadêmica')),
                ('func_salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='salário')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('prof', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operacional.profissao', verbose_name='profissão')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'ordering': ['func_nome'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('tur_nome', models.CharField(max_length=100, unique=True, verbose_name='nome da turma')),
                ('tur_horario', models.CharField(max_length=50, verbose_name='horário')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.funcionario', verbose_name='professor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turma',
                'ordering': ['tur_nome'],
            },
        ),
        migrations.CreateModel(
            name='TurmaAlunos',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tual_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_matricula', models.DateField(verbose_name='data de matrícula')),
                ('ativo', models.BooleanField(default=True, verbose_name='matrícula ativa')),
                ('alu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.aluno', verbose_name='aluno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.turma', verbose_name='turma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'turma_alunos',
                'ordering': ['tur', 'alu__alu_nome'],
                'unique_together': {('tur', 'alu')},
            },
        ),
    ]
