# Generated by Django 5.1.15 on 2026-04-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='func',
        ),
    ]
