# Generated by Django 5.1.15 on 2026-04-10 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_remove_turma_func'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaAluno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fial_id', models.AutoField(primary_key=True, serialize=False)),
                ('fial_data', models.DateField(verbose_name='data da avaliação')),
                ('fial_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso (kg)')),
                ('fial_massa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='massa muscular (kg)')),
                ('fial_massa_gorda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='massa gorda (kg)')),
                ('fial_porcentagem_gordura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% gordura')),
                ('fial_circunferencia_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='circunferência abdominal (cm)')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fichas', to='operacional.aluno', verbose_name='aluno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha do Aluno',
                'verbose_name_plural': 'Fichas dos Alunos',
                'db_table': 'ficha_aluno',
                'ordering': ['-fial_data'],
            },
        ),
    ]
