# Generated by Django 5.1.15 on 2026-04-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_phase31_round1_adicoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='alu_circunferencia_abdominal',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alu_massa_gorda',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alu_massa_muscular',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alu_peso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='alu_porcentagem_gordura',
        ),
    ]
