# Generated by Django 5.1.15 on 2026-04-23 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0006_turma_tur_modalidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoFalta',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('avi_id', models.AutoField(primary_key=True, serialize=False)),
                ('avi_data_hora_aviso', models.DateTimeField(verbose_name='quando o aluno avisou')),
                ('avi_data_aula', models.DateField(verbose_name='data da aula')),
                ('avi_tipo', models.CharField(choices=[('justificada', 'Justificada'), ('atestado', 'Atestado Médico')], max_length=20, verbose_name='tipo')),
                ('avi_antecedencia_horas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='antecedência (horas)')),
                ('avi_gera_credito', models.BooleanField(default=False, verbose_name='gera crédito?')),
                ('avi_observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_falta', to='operacional.aluno', verbose_name='aluno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_falta', to='operacional.turma', verbose_name='turma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso de Falta',
                'verbose_name_plural': 'Avisos de Falta',
                'db_table': 'aviso_falta',
                'ordering': ['-avi_data_hora_aviso'],
            },
        ),
    ]
