# Generated by Django 5.1.15 on 2026-04-23 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('operacional', '0007_fase8_aviso_falta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planospagamentos',
            options={'ordering': ['serv__serv_nome', 'plan_tipo_plano'], 'verbose_name': 'Plano de Pagamento', 'verbose_name_plural': 'Planos de Pagamento'},
        ),
        migrations.AlterField(
            model_name='planospagamentos',
            name='alu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacional.aluno', verbose_name='aluno'),
        ),
        migrations.AlterField(
            model_name='planospagamentos',
            name='plan_data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='data de início'),
        ),
        migrations.CreateModel(
            name='AlunoPlano',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aplano_id', models.AutoField(primary_key=True, serialize=False)),
                ('aplano_data_inicio', models.DateField(verbose_name='data de início')),
                ('aplano_data_fim', models.DateField(blank=True, null=True, verbose_name='data de término')),
                ('aplano_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('aplano_observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='operacional.aluno', verbose_name='aluno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='financeiro.planospagamentos', verbose_name='plano')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano do Aluno',
                'verbose_name_plural': 'Planos dos Alunos',
                'db_table': 'aluno_plano',
                'ordering': ['-aplano_data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='aplano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobranças', to='financeiro.alunoplano', verbose_name='plano do aluno'),
        ),
    ]
