# Generated by Django 5.1.15 on 2026-04-23 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_fase9_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planospagamentos',
            name='alu',
        ),
        migrations.RemoveField(
            model_name='planospagamentos',
            name='plan_ativo',
        ),
        migrations.RemoveField(
            model_name='planospagamentos',
            name='plan_data_fim',
        ),
        migrations.RemoveField(
            model_name='planospagamentos',
            name='plan_data_inicio',
        ),
    ]
