# Generated by Django 5.1.15 on 2026-04-04 15:59

import apps.tecnico.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operacional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aul_id', models.AutoField(primary_key=True, serialize=False)),
                ('aul_data', models.DateField(verbose_name='data da aula')),
                ('aul_hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('aul_hora_final', models.TimeField(blank=True, null=True, verbose_name='hora de término')),
                ('aul_pressao_inicio', models.CharField(blank=True, max_length=10, null=True, validators=[apps.tecnico.models.validar_pressao_arterial], verbose_name='pressão inicial')),
                ('aul_pressao_final', models.CharField(blank=True, max_length=10, null=True, validators=[apps.tecnico.models.validar_pressao_arterial], verbose_name='pressão final')),
                ('aul_tipo_presenca', models.CharField(choices=[('regular', 'Regular'), ('falta', 'Falta'), ('reposicao', 'Reposição')], default='regular', max_length=20, verbose_name='tipo de presença')),
                ('aul_tipo_falta', models.CharField(blank=True, choices=[('sem_aviso', 'Sem aviso'), ('justificada', 'Justificada (1h–48h antes)'), ('atestado', 'Atestado médico'), ('cenario3', 'Aviso com mais de 48h (pendente)')], max_length=20, null=True, verbose_name='tipo de falta')),
                ('aul_intensidade_esforco', models.IntegerField(blank=True, null=True, verbose_name='intensidade de esforço (0–10)')),
                ('alu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.aluno', verbose_name='aluno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.turma', verbose_name='turma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aulas',
                'ordering': ['-aul_data', '-aul_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CreditoReposicao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cred_id', models.AutoField(primary_key=True, serialize=False)),
                ('cred_data_geracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de geração')),
                ('cred_data_expiracao', models.DateTimeField(verbose_name='data de expiração')),
                ('cred_usado', models.BooleanField(default=False, verbose_name='crédito usado')),
                ('cred_status', models.CharField(choices=[('disponivel', 'Disponível'), ('usado', 'Usado'), ('expirado', 'Expirado')], default='disponivel', max_length=20, verbose_name='status')),
                ('alu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.aluno', verbose_name='aluno')),
                ('aula_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos_gerados', to='tecnico.aula', verbose_name='aula de origem (falta)')),
                ('aula_reposicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_utilizados', to='tecnico.aula', verbose_name='aula de reposição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédito de Reposição',
                'verbose_name_plural': 'Créditos de Reposição',
                'db_table': 'creditos_reposicao',
                'ordering': ['cred_data_expiracao'],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='cred',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnico.creditoreposicao', verbose_name='crédito utilizado'),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exe_id', models.AutoField(primary_key=True, serialize=False)),
                ('exe_nome', models.CharField(max_length=125, verbose_name='nome do exercício')),
                ('exe_aparelho', models.CharField(choices=[('solo', 'Solo'), ('reformer', 'Reformer'), ('cadillac', 'Cadillac'), ('chair', 'Chair'), ('barrel', 'Barrel')], max_length=20, verbose_name='aparelho')),
                ('exe_descricao_tecnica', models.TextField(blank=True, null=True, verbose_name='descrição técnica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'db_table': 'exercicios',
                'ordering': ['exe_nome', 'exe_aparelho'],
            },
        ),
        migrations.CreateModel(
            name='FichaTreino',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fitr_id', models.AutoField(primary_key=True, serialize=False)),
                ('fitr_nome', models.CharField(max_length=150, verbose_name='nome da ficha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Treino',
                'verbose_name_plural': 'Fichas de Treino',
                'db_table': 'ficha_treino',
                'ordering': ['fitr_nome'],
            },
        ),
        migrations.AddField(
            model_name='aula',
            name='fitr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tecnico.fichatreino', verbose_name='ficha de treino'),
        ),
        migrations.CreateModel(
            name='FichaTreinoExercicios',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ftex_id', models.AutoField(primary_key=True, serialize=False)),
                ('ftex_ordem', models.IntegerField(verbose_name='ordem na ficha')),
                ('ftex_repeticoes', models.IntegerField(verbose_name='repetições')),
                ('ftex_series', models.IntegerField(blank=True, null=True, verbose_name='séries')),
                ('ftex_observacoes', models.TextField(blank=True, null=True, verbose_name='observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('exe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tecnico.exercicio', verbose_name='exercício')),
                ('fitr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tecnico.fichatreino', verbose_name='ficha de treino')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercício da Ficha',
                'verbose_name_plural': 'Exercícios da Ficha',
                'db_table': 'ficha_treino_exercicios',
                'ordering': ['fitr', 'ftex_ordem'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('tur', 'alu', 'aul_data', 'aul_hora_inicio')},
        ),
    ]
