# Generated by Django 5.1.15 on 2026-04-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0002_remove_turma_func'),
        ('tecnico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacional.funcionario', verbose_name='professor'),
        ),
    ]
