# Generated by Django 5.1.15 on 2026-04-10 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0002_aula_func'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercicio',
            options={'ordering': ['exe_nome'], 'verbose_name': 'Exercício', 'verbose_name_plural': 'Exercícios'},
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exe_acessorio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='acessório'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exe_modalidade',
            field=models.CharField(choices=[('pilates', 'Mat Pilates'), ('funcional', 'Funcional')], default='pilates', max_length=20, verbose_name='modalidade'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exe_variacao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='variação'),
        ),
        migrations.AddField(
            model_name='fichatreino',
            name='fitr_modalidade',
            field=models.CharField(blank=True, choices=[('pilates', 'Mat Pilates'), ('funcional', 'Funcional')], max_length=20, null=True, verbose_name='modalidade'),
        ),
        migrations.AddField(
            model_name='fichatreinoexercicios',
            name='ftex_secao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='seção'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='exe_aparelho',
            field=models.CharField(choices=[('solo', 'Solo'), ('reformer', 'Reformer'), ('cadillac', 'Cadillac'), ('chair', 'Chair'), ('barrel', 'Barrel')], max_length=20, verbose_name='aparelho (legado)'),
        ),
        migrations.CreateModel(
            name='Aparelho',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('apar_id', models.AutoField(primary_key=True, serialize=False)),
                ('apar_nome', models.CharField(max_length=100, verbose_name='nome')),
                ('apar_modalidade', models.CharField(choices=[('pilates', 'Mat Pilates'), ('funcional', 'Funcional'), ('ambos', 'Ambos')], max_length=20, verbose_name='modalidade')),
                ('apar_ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aparelho',
                'verbose_name_plural': 'Aparelhos',
                'db_table': 'aparelho',
                'ordering': ['apar_modalidade', 'apar_nome'],
            },
        ),
        migrations.AddField(
            model_name='exercicio',
            name='exe_aparelho_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exercicios', to='tecnico.aparelho', verbose_name='aparelho'),
        ),
    ]
