# Generated by Django 5.1.15 on 2026-04-10 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0004_phase31_round2_data_aparelhos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='exe_aparelho',
        ),
    ]
