# Generated by Django 5.1.15 on 2026-04-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0006_phase31_round4_rename_aparelho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='exe_modalidade',
            field=models.CharField(choices=[('pilates', 'Mat Pilates'), ('funcional', 'Funcional')], max_length=20, verbose_name='modalidade'),
        ),
    ]
