# Generated by Django 5.1.15 on 2026-04-11 01:27
# Fix aplicado em 2026-04-11: renomeia constraints aulas_* em ministrar_aula
# antes de criar a nova tabela aulas (evita conflito de nomes herdados da Fase 3.2)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0005_aluno_saude_emergencia'),
        ('tecnico', '0014_phase32_ministrar_aula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 0. Remove ghost migration criada pelo entrypoint no deploy anterior
        migrations.RunSQL(
            sql="DELETE FROM django_migrations WHERE app='tecnico' AND name='0015_alter_ministraraula_options';",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # 1. Renomeia constraints E indexes herdados de `aulas` (antigo model Aula)
        #    que ficaram em ministrar_aula com prefixo aulas_*
        migrations.RunSQL(
            sql="""
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_pkey                                          TO ministraraula_pkey;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_alu_id_9546a407_fk_alunos_alu_id              TO ministraraula_alu_id_9546a407_fk_alunos_alu_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_cred_id_ea292819_fk_creditos_reposicao_cred_id TO ministraraula_cred_id_ea292819_fk_creditos_reposicao_cred_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_created_by_id_e69c67fe_fk_users_id            TO ministraraula_created_by_id_e69c67fe_fk_users_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_deleted_by_id_6b6a8d95_fk_users_id            TO ministraraula_deleted_by_id_6b6a8d95_fk_users_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_fitr_id_073f0f10_fk_ficha_treino_fitr_id       TO ministraraula_fitr_id_073f0f10_fk_ficha_treino_fitr_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_func_id_bb074bbd_fk_funcionario_func_id        TO ministraraula_func_id_bb074bbd_fk_funcionario_func_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_tur_id_9ddbdb66_fk_turma_tur_id                TO ministraraula_tur_id_9ddbdb66_fk_turma_tur_id;
                ALTER TABLE ministrar_aula RENAME CONSTRAINT aulas_updated_by_id_fb485fa4_fk_users_id             TO ministraraula_updated_by_id_fb485fa4_fk_users_id;
                ALTER INDEX aulas_alu_id_9546a407      RENAME TO ministraraula_alu_id_9546a407;
                ALTER INDEX aulas_created_by_id_e69c67fe RENAME TO ministraraula_created_by_id_e69c67fe;
                ALTER INDEX aulas_deleted_by_id_6b6a8d95 RENAME TO ministraraula_deleted_by_id_6b6a8d95;
                ALTER INDEX aulas_tur_id_9ddbdb66      RENAME TO ministraraula_tur_id_9ddbdb66;
                ALTER INDEX aulas_updated_by_id_fb485fa4 RENAME TO ministraraula_updated_by_id_fb485fa4;
                ALTER INDEX aulas_cred_id_ea292819     RENAME TO ministraraula_cred_id_ea292819;
                ALTER INDEX aulas_fitr_id_073f0f10     RENAME TO ministraraula_fitr_id_073f0f10;
                ALTER INDEX aulas_func_id_bb074bbd     RENAME TO ministraraula_func_id_bb074bbd;
                ALTER SEQUENCE aulas_aul_id_seq        RENAME TO ministraraula_miau_id_seq;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AlterModelOptions(
            name='ministraraula',
            options={'ordering': ['-miau_data', '-miau_hora_inicio'], 'verbose_name': 'Registro de Aula', 'verbose_name_plural': 'Registros de Aula'},
        ),
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aul_id', models.AutoField(primary_key=True, serialize=False)),
                ('aul_data', models.DateField(verbose_name='data da aula')),
                ('aul_hora_inicio', models.TimeField(verbose_name='hora de início')),
                ('aul_hora_final', models.TimeField(blank=True, null=True, verbose_name='hora de término')),
                ('aul_modalidade', models.CharField(choices=[('pilates', 'Mat Pilates'), ('funcional', 'Funcional')], max_length=20, verbose_name='modalidade')),
                ('aul_nome', models.CharField(blank=True, help_text='Ex: "Funcional Seg 17:00" — preenchido automaticamente se deixado em branco', max_length=150, null=True, verbose_name='nome/descrição')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('func', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operacional.funcionario', verbose_name='professor')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operacional.turma', verbose_name='turma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'db_table': 'aulas',
                'ordering': ['-aul_data', '-aul_hora_inicio'],
                'unique_together': {('tur', 'aul_data', 'aul_modalidade')},
            },
        ),
        migrations.AddField(
            model_name='ministraraula',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='tecnico.aulas', verbose_name='aula'),
        ),
    ]
