# Generated by Django 5.1.15 on 2026-04-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0014_phase32_ministrar_aula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministraraula',
            options={'ordering': ['-miau_data', '-miau_hora_inicio'], 'verbose_name': 'Registro de Aula', 'verbose_name_plural': 'Registros de Aula'},
        ),
    ]
