# Generated by Django 5.1.15 on 2026-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0018_backfill_ministrar_aula_aula_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aulas',
            options={'ordering': ['-aul_data'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
    ]
