# Generated by Django 5.1.15 on 2026-04-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0019_alter_aulas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='aul_hora_final',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de término'),
        ),
        migrations.AddField(
            model_name='aulas',
            name='aul_hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de início'),
        ),
    ]
