# Generated by Django 5.1.15 on 2026-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0022_fase4_aula_obrigatoria_e_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministraraula',
            name='miau_hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de início'),
        ),
    ]
