# Generated by Django 5.1.15 on 2026-04-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnico', '0023_fase4_hora_inicio_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministraraula',
            name='miau_hora_final',
        ),
        migrations.RemoveField(
            model_name='ministraraula',
            name='miau_hora_inicio',
        ),
    ]
